---
title: "v02_Disproportionality_Analysis"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{v02_Disproportionality_Analysis}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---



This tutorial will show you how to perform simple and advanced disproportionality analyses. While this tutorial recursively redefine the object of study and the background reference group, it does so to provide a pedagogical flow. It is recommended to design the analysis a priori, and clearly document and justify any deviation from the original design.

## Requisites

This tutorial requires that you have first:

1.  installed R and R Studio,

2.  installed the DiAna package,

3.  and set up your project folder.

Otherwise get back to the ReadMe and follow the instructions.

It is also recommended, but not necessary, that you have read the previous vignettes.

## Start the subproject

From the DiAna main project, we open a new R script and run the snippet 'new_FAERS_project' to set up a project.


```
#> Error in paste0(here::here, "\figure\render_forest-1.png"): cannot coerce type 'closure' to vector of type 'character'
```
