#' Retrieve Pregnancy-Related Report Identifiers from FAERS
#'
#' This function retrieves the identifiers of pregnancy-related reports from the FDA Adverse Event Reporting System (FAERS) for a specified quarter.
#'
#' @param quarter A character string specifying the FAERS quarter to retrieve data for. Default is the current FAERS version (\code{FAERS_version}).
#' @return A list containing four elements:
#' \describe{
#'   \item{\code{high_specificity}}{A vector of identifiers with high specificity for pregnancy-related reports.}
#'   \item{\code{medium_specificity}}{A vector of identifiers with medium specificity for pregnancy-related reports.}
#'   \item{\code{low_specificity}}{A vector of identifiers with low specificity for pregnancy-related reports.}
#'   \item{\code{paternal_exposure}}{A vector of identifiers for paternal exposure-related reports.}
#' }
#' @details
#' The function processes data from multiple FAERS tables (\code{DEMO}, \code{DRUG}, \code{REAC}, \code{INDI}, \code{OUTC}, \code{THER}, and \code{DRUG_SUPP}) to identify pregnancy-related reports based on specific indications, reactions, and drug routes. The results are filtered to exclude reports unlikely to be related to pregnancy (e.g., reports involving males, children, or older adults). The algorithm is an implementation and evolution of the original pregnancy algorithm by Sakai,ref. 10.3389/fphar.2022.1063625
#' #' @references
#' Sakai T, Mori C, Ohtsu F. Potential safety signal of pregnancy loss with vascular endothelial growth factor inhibitor intraocular injection: A disproportionality analysis using the Food and Drug Administration Adverse Event Reporting System. Front Pharmacol. 2022 Nov 10;13:1063625. doi: 10.3389/fphar.2022.1063625. PMID: 36438807; PMCID: PMC9684212.
#' @export
#' @examples
#' \dontrun{
#' # Retrieve pregnancy-related report identifiers for the default quarter
#' FAERS_version <- "23Q4"
#' pids_pregnancy <- retrieve_pregnancy_pids()
#' pids_pregnancy$medium_specificity
#' }
retrieve_pregnancy_pids <- function(quarter = FAERS_version) {
  ## pregnancy indication--------------
  pregnancy_indication <- c(
    "abnormal cord insertion", "abnormal labour", "abnormal labour affecting foetus",
    "acute fatty liver of pregnancy", "afterbirth pain", "amniocentesis abnormal",
    "amniorrhexis", "amniorrhoea", "amnioscopy abnormal", "amniotic cavity disorder",
    "amniotic cavity infection", "amniotic fluid erythropoietin level increased",
    "amniotic fluid index abnormal", "amniotic fluid index decreased",
    "amniotic fluid index increased", "amniotic fluid volume decreased",
    "amniotic fluid volume increased", "amniotic infection syndrome of blane",
    "amniotic membrane rupture test positive", "anaemia of pregnancy",
    "anaphylactoid syndrome of pregnancy", "angiotensin ii receptor type 1 antibody positive",
    "arrested labour", "artificial rupture of membranes", "assisted delivery",
    "asynclitic presentation", "bacteriuria in pregnancy", "benign hydatidiform mole",
    "bimanual uterine compression", "biopsy chorionic villous abnormal",
    "blood type incompatibility", "breech delivery", "breech extraction",
    "breech presentation", "brief psychotic disorder, with postpartum onset",
    "brow presentation", "caesarean section", "cephalo-pelvic disproportion",
    "cervical incompetence", "cervix cerclage procedure", "cervix dystocia",
    "cervix scarring", "chloasma", "cholestasis of pregnancy", "chorioamniotic separation",
    "chronic villitis of unknown etiology", "complication of delivery",
    "complication of pregnancy", "decidual cast", "delayed delivery",
    "delivery outside health facility", "diabetes complicating pregnancy",
    "discordant twin", "drug dependence, antepartum", "drug dependence, postpartum",
    "drug exposure before pregnancy", "drug use disorder, antepartum",
    "drug use disorder, postpartum", "eclampsia", "ectopic pregnancy",
    "ectopic pregnancy termination", "ectopic pregnancy under hormonal contraception",
    "ectopic pregnancy with contraceptive device", "elderly primigravida",
    "endometritis bacterial", "endometritis decidual", "excessive maternal gestational weight gain",
    "exposure during pregnancy", "exposure via father", "external cephalic version",
    "face presentation", "failed forceps delivery", "failed induction of labour",
    "failed trial of labour", "false labour", "foetal arm prolapse",
    "foetal dystocia", "foetal exposure during delivery", "foetal exposure during pregnancy",
    "foetal exposure timing unspecified", "foetal malposition", "foetal malpresentation",
    "foetal monitoring abnormal", "foetal vascular malperfusion",
    "forceps delivery", "gestational diabetes", "gestational hypertension",
    "gestational oedema", "gestational trophoblastic detachment",
    "glucose tolerance impaired in pregnancy", "glycosuria during pregnancy",
    "haemorrhage in pregnancy", "hellp syndrome", "herpes gestationis",
    "heterotopic pregnancy", "high foetal head", "high risk pregnancy",
    "hyperemesis gravidarum", "hyperreactio luteinalis", "impetigo herpetiformis",
    "incoordinate uterine action", "induced labour", "inferior vena cava syndrome",
    "intrapartum haemorrhage", "intrauterine infection", "kleihauer-betke test positive",
    "labour augmentation", "labour complication", "labour induction",
    "labour stimulation", "large for dates baby", "lochial infection",
    "lochiostasis", "locked twins", "lymphocytic hypophysitis", "malignant hydatidiform mole",
    "malignant neoplasm of placenta", "mastitis postpartum", "maternal alcohol use",
    "maternal body mass index decreased", "maternal body mass index increased",
    "maternal cancer in pregnancy", "maternal death", "maternal distress during labour",
    "maternal exposure before pregnancy", "maternal exposure during pregnancy",
    "maternal exposure timing unspecified", "maternal exposure via partner during pregnancy",
    "maternal pre-pregnancy obesity", "maternal pre-pregnancy underweight",
    "maternal therapy to enhance foetal lung maturity", "medically induced preterm birth",
    "metastases to placenta", "mirror syndrome", "missed labour",
    "morning sickness", "multiple pregnancy", "oblique presentation",
    "obstetric infection", "obstetric procedure complication", "obstetrical pulmonary embolism",
    "obstetrical tetanus", "obstructed labour", "oligohydramnios",
    "omphalorrhexis", "paternal exposure before pregnancy", "paternal exposure during pregnancy",
    "paternal exposure timing unspecified", "pelvic girdle pain",
    "pelvic haematoma obstetric", "perineal repair breakdown", "peripartum cardiomyopathy",
    "peripartum haemorrhage", "placenta accreta", "placenta duplex",
    "placenta praevia", "placenta praevia haemorrhage", "placental calcification",
    "placental chorioangioma", "placental cyst", "placental disorder",
    "placental dysplasia", "placental hypertrophy", "placental infarction",
    "placental insufficiency", "placental lake", "placental necrosis",
    "placental neoplasm", "placental polyp", "placental transfusion syndrome",
    "polyhydramnios", "polymorphic eruption of pregnancy", "postpartum anxiety",
    "postpartum disorder", "postpartum haemorrhage", "postpartum hypopituitarism",
    "postpartum neurosis", "postpartum sepsis", "postpartum stress disorder",
    "postpartum thrombosis", "postpartum uterine subinvolution",
    "postpartum venous thrombosis", "precipitate labour", "pre-eclampsia",
    "pregnancy in habitual aborter", "pregnancy of unknown location",
    "pregnancy related infection", "pregnancy with advanced maternal age",
    "pregnancy with young maternal age", "premature delivery", "premature labour",
    "premature rupture of membranes", "premature separation of placenta",
    "prenatal screening test abnormal", "preterm premature rupture of membranes",
    "previous caesarean section", "prolonged labour", "prolonged pregnancy",
    "prolonged rupture of membranes", "prophylaxis against rh isoimmunisation",
    "prophylaxis of abortion", "puerperal infection", "puerperal pyrexia",
    "renal disorder in pregnancy", "retained placenta operation",
    "retained placenta or membranes", "retained products of conception",
    "retroplacental haematoma", "rhesus incompatibility", "risk of future pregnancy miscarriage",
    "rubella in pregnancy", "ruptured ectopic pregnancy", "short interpregnancy interval",
    "shortened cervix", "shoulder dystocia", "silent thyroiditis",
    "small size placenta", "subchorionic haematoma", "subchorionic haemorrhage",
    "superimposed pre-eclampsia", "symphysiotomy", "third stage postpartum haemorrhage",
    "threatened labour", "threatened uterine rupture", "thyroid dysfunction in pregnancy",
    "tocolysis", "tracheloplasty", "transverse presentation", "traumatic delivery",
    "tubal rupture", "twin pregnancy", "ultrasound antenatal screen abnormal",
    "umbilical artery vascular resistance increased", "umbilical cord abnormality",
    "umbilical cord around neck", "umbilical cord compression", "umbilical cord cyst",
    "umbilical cord haemorrhage", "umbilical cord prolapse", "umbilical cord short",
    "umbilical cord thrombosis", "umbilical cord vascular disorder",
    "unstable foetal lie", "uterine adhesions", "uterine atony",
    "uterine cervix stenosis", "uterine compression sutures", "uterine contractions abnormal",
    "uterine contractions during pregnancy", "uterine dehiscence",
    "uterine hyperstimulation", "uterine hypertonus", "uterine hypokinesia",
    "uterine hypotonus", "uterine inversion", "uterine irritability",
    "uterine malposition", "uterine rupture", "uterine tachysystole",
    "vacuum extractor delivery", "vaginal tamponade", "vasa praevia",
    "venous thrombosis in pregnancy", "alpha 1 foetoprotein amniotic fluid abnormal",
    "alpha 1 foetoprotein amniotic fluid decreased", "alpha 1 foetoprotein amniotic fluid increased",
    "amniocentesis abnormal", "amniorrhexis", "amniorrhoea", "amnioscopy abnormal",
    "amniotic cavity disorder", "amniotic cavity infection", "amniotic fluid erythropoietin level increased",
    "amniotic fluid index abnormal", "amniotic fluid volume decreased",
    "amniotic fluid volume increased", "amniotic infection syndrome of blane",
    "anaesthetic complication foetal", "angiotensin converting enzyme inhibitor foetopathy",
    "baseline foetal heart rate variability disorder", "biopsy chorionic villous abnormal",
    "biopsy foetal abnormal", "bradycardia foetal", "cerebral haemorrhage foetal",
    "cerebral infarction foetal", "chronic villitis of unknown etiology",
    "cordocentesis", "diabetic foetopathy", "diethylstilboestrol syndrome",
    "discordant twin", "ductus arteriosus stenosis foetal", "enlarged foetal cisterna magna",
    "erythroblastosis foetalis", "foetal acidosis", "foetal alcohol syndrome",
    "foetal anaemia", "foetal anticonvulsant syndrome", "foetal arrhythmia",
    "foetal biophysical profile score abnormal", "foetal biophysical profile score equivocal",
    "foetal cardiac arrest", "foetal cardiac disorder", "foetal cerebrovascular disorder",
    "foetal chromosome abnormality", "foetal compartment fluid collection",
    "foetal cystic hygroma", "foetal damage", "foetal disorder",
    "foetal distress syndrome", "foetal gastrointestinal tract imaging abnormal",
    "foetal growth abnormality", "foetal growth restriction", "foetal heart rate abnormal",
    "foetal heart rate acceleration abnormality", "foetal heart rate deceleration abnormality",
    "foetal heart rate decreased", "foetal heart rate disorder",
    "foetal heart rate increased", "foetal heart rate indeterminate",
    "foetal hypokinesia", "foetal macrosomia", "foetal malformation",
    "foetal malnutrition", "foetal megacystis", "foetal methotrexate syndrome",
    "foetal monitoring abnormal", "foetal movement disorder", "foetal musculoskeletal imaging abnormal",
    "foetal non-stress test abnormal", "foetal renal imaging abnormal",
    "foetal renal impairment", "foetal retinoid syndrome", "foetal surgery",
    "foetal tachyarrhythmia", "foetal therapeutic procedure", "foetal tobacco syndrome",
    "foetal vascular malperfusion", "foetal warfarin syndrome", "foetal-maternal haemorrhage",
    "gestational age test abnormal", "haemorrhage foetal", "hydrops foetalis",
    "hypocalvaria", "hypopituitarism foetal", "increased foetal movements",
    "intrauterine infection", "maternal condition affecting foetus",
    "maternal death affecting foetus", "maternal drugs affecting foetus",
    "maternal hypertension affecting foetus", "meconium in amniotic fluid",
    "meconium increased", "meconium peritonitis", "meconium stain",
    "mirror syndrome", "nonreassuring foetal heart rate pattern",
    "oligohydramnios", "omphalorrhexis", "paternal drugs affecting foetus",
    "polyhydramnios", "prenatal screening test abnormal", "radiation injury affecting foetus",
    "sinusoidal foetal heart rate pattern", "tachycardia foetal",
    "thalidomide embryopathy", "twin reversed arterial perfusion sequence malformation",
    "ultrasound antenatal screen abnormal", "ultrasound foetal abnormal",
    "umbilical artery vascular resistance increased", "umbilical cord abnormality",
    "umbilical cord around neck", "umbilical cord compression", "umbilical cord cyst",
    "umbilical cord haemorrhage", "umbilical cord occlusion", "umbilical cord prolapse",
    "umbilical cord short", "umbilical cord thrombosis", "umbilical cord vascular disorder",
    "vesicoamniotic shunt", "virilism foetal", "alpha 1 foetoprotein amniotic fluid normal",
    "amniocentesis normal", "amnioscopy normal", "amniotic fluid index normal",
    "biopsy foetal normal", "birth weight normal", "caesarean delivery on maternal request",
    "cervical dilatation", "chloasma", "delivery", "false negative pregnancy test",
    "first trimester pregnancy", "foetal heart rate normal", "human chorionic gonadotropin increased",
    "human chorionic gonadotropin positive", "labour pain", "live birth",
    "multigravida", "multiparous", "newborn head moulding", "normal foetus",
    "normal labour", "normal newborn", "nulliparous", "parity", "planning to become pregnant",
    "postpartum state", "pregnancy", "pregnancy after post coital contraception",
    "pregnancy of partner", "pregnancy on contraceptive", "pregnancy on oral contraceptive",
    "pregnancy test positive", "pregnancy test urine positive", "pregnancy with contraceptive device",
    "pregnancy with contraceptive patch", "pregnancy with implant contraceptive",
    "pregnancy with injectable contraceptive", "prenatal care", "primigravida",
    "primiparous", "second trimester pregnancy", "spontaneous rupture of membranes",
    "term baby", "term birth", "third trimester pregnancy", "ultrasound antenatal screen normal",
    "unintended pregnancy", "unwanted pregnancy", "uterine contractions during pregnancy"
  )

  ## child def ------------------------
  child_def <- c(
    "11-beta-hydroxylase deficiency", "17,20-desmolase deficiency",
    "17-alpha-hydroxylase deficiency", "18q minus syndrome", "1p36 deletion syndrome",
    "20,22-desmolase deficiency", "21-hydroxylase deficiency", "22q11.2 deletion syndrome",
    "2-hydroxyglutaric aciduria", "3-hydroxyacetyl-coenzyme a dehydrogenase deficiency",
    "3m syndrome", "5-alpha-reductase deficiency", "aase syndrome",
    "abdominal transposition", "abdominal wall anomaly", "aberrant aortic arch",
    "abetalipoproteinaemia", "ablepharon macrostomia syndrome", "abnormal dna methylation",
    "abnormal palmar/plantar creases", "abo haemolytic disease of newborn",
    "acad9 deficiency", "acatalasaemia", "accessory auricle", "accessory breast",
    "accessory carpal bone", "accessory kidney", "accessory liver lobe",
    "accessory muscle", "accessory navicular syndrome", "accessory renal artery",
    "accessory salivary gland", "accessory spleen", "acetylcholinesterase deficiency",
    "achard thiers syndrome", "achromotrichia congenital", "acquired chromosomal abnormality",
    "acquired gene mutation", "acquired mitochondrial dna deletion",
    "acquired mitochondrial dna mutation", "acral peeling skin syndrome",
    "acrocallosal syndrome", "acrocephalosyndactyly", "acrodermatitis enteropathica",
    "acrodysostosis", "acrokeratosis verruciformis", "acromesomelic dysplasia",
    "acromicric dysplasia", "activated pi3 kinase delta syndrome",
    "adactyly", "adams-oliver syndrome", "adcy5-related dyskinesia",
    "adenine phosphoribosyl transferase deficiency", "adenomatous polyposis coli",
    "adenylosuccinate lyase deficiency", "adnp syndrome", "adrenal insufficiency neonatal",
    "adrenogenital syndrome", "adrenoleukodystrophy", "adsl gene mutation",
    "adult polyglucosan body disease", "aglossia", "aicardi-goutieres syndrome",
    "aicardi's syndrome", "aids dysmorphic syndrome", "alagille syndrome",
    "albinism", "albright's disease", "alexander disease", "alkaptonuria",
    "allan-herndon-dudley syndrome", "alpers disease", "alpha-1 antitrypsin deficiency",
    "alpha-mannosidosis", "alpha-thalassaemia-intellectual deficit syndrome",
    "alport's syndrome", "alstroem syndrome", "alternating hemiplegia of childhood",
    "alveolar capillary dysplasia", "amastia", "amblyopia congenital",
    "amegakaryocytic thrombocytopenia", "aminoaciduria", "amniotic band syndrome",
    "amyotrophic lateral sclerosis gene carrier", "anal atresia",
    "anaplastic lymphoma kinase gene and nucleophosmin gene fusion overexpression",
    "anaplastic lymphoma kinase gene mutation", "andersen-tawil syndrome",
    "androgen insensitivity syndrome", "androgen receptor gene overexpression",
    "anencephaly", "angelman's syndrome", "angiotensin converting enzyme inhibitor foetopathy",
    "aniridia", "aniridia-cerebellar ataxia-mental deficiency", "ankyloglossia congenital",
    "annular pancreas", "anodontia", "anomalous arrangement of pancreaticobiliary duct",
    "anomalous pulmonary venous connection", "anomaly of external ear congenital",
    "anomaly of middle ear congenital", "anomaly of orbit, congenital",
    "anophthalmos", "anorchism", "anorectal agenesis", "anorectal malformation",
    "anotia", "anterior chamber cleavage syndrome", "anterior displaced anus",
    "antithrombin iii deficiency", "antley-bixler syndrome", "aorta hypoplasia",
    "aortic valve atresia", "aorticopulmonary septal defect", "aphakia congenital",
    "aphallia", "aplasia", "aplasia cutis congenita", "apolipoprotein e e4 gene carrier",
    "apparent mineralocorticoid excess", "arachnodactyly", "arcuate foramen",
    "arginase deficiency", "argininosuccinate lyase deficiency",
    "argininosuccinate synthetase deficiency", "arhinencephaly",
    "arnold-chiari malformation", "aromatic l-amino acid decarboxylase deficiency",
    "arrhythmogenic right ventricular dysplasia", "arterial tortuosity syndrome",
    "arteriovenous malformation", "asah1 related disorder", "ash leaf macule",
    "aspartate-glutamate-transporter deficiency", "aspartylglucosaminuria",
    "asphyxiating thoracic dystrophy", "asplenia", "asxl1 gene mutation",
    "asymmetric crying facies", "asymmetric thigh fold", "asymptomatic gene carrier",
    "ataxia telangiectasia", "athelia", "atrial septal defect", "atrioventricular node dispersion",
    "atrioventricular septal defect", "auditory neuropathy spectrum disorder",
    "autoimmune lymphoproliferative syndrome", "autoinflammation with infantile enterocolitis",
    "autosomal chromosome anomaly", "autosomal recessive megaloblastic anaemia",
    "azygos lobe", "baller-gerold syndrome", "baltic myoclonic epilepsy",
    "bannayan-riley-ruvalcaba syndrome", "baraitser rodeck garner syndrome",
    "barakat syndrome", "bard 1 gene mutation", "barth syndrome",
    "bartter's syndrome", "basal cell naevus syndrome", "bcor gene mutation",
    "becker's muscular dystrophy", "beckwith-wiedemann syndrome",
    "benign congenital hypotonia", "benign familial haematuria",
    "benign familial neonatal convulsions", "benign familial pemphigus",
    "benign recurrent intrahepatic cholestasis", "benjamin syndrome",
    "berdon's syndrome", "bergmeister's papilla", "bernard-soulier syndrome",
    "beta ketothiolase deficiency", "bicuspid aortic valve", "bicuspid pulmonary valve",
    "bifid ureter", "biliary hamartoma", "biotinidase deficiency",
    "birth mark", "birt-hogg-dube syndrome", "bladder agenesis",
    "blau syndrome", "blepharophimosis congenital", "blindness congenital",
    "bloch-sulzberger syndrome", "block vertebra", "blood incompatibility haemolytic anaemia of newborn",
    "bloom syndrome", "blys polymorphism", "bosch-boonstra-schaaf optic atrophy syndrome",
    "bpes syndrome", "brachycephaly", "brachydactyly", "brachymetatarsia",
    "brachyolmia", "braf gene mutation", "brain malformation", "branchial cleft sinus",
    "branchial cyst", "branchiogenic syndrome", "branchio-oto-renal syndrome",
    "brca1 gene mutation", "brca2 gene mutation", "breast malformation",
    "bronchial atresia", "bronchogenic cyst", "brown-vialetto-van laere syndrome",
    "brugada syndrome", "brunner syndrome", "bruton's agammaglobulinaemia",
    "bulbospinal muscular atrophy congenital", "buried penis syndrome",
    "cadasil", "calr gene mutation", "campomelic syndrome", "camptodactyly congenital",
    "camptodactyly-arthropathy-coxa vara-pericarditis syndrome",
    "camptomelia", "canavan disease", "cancer gene carrier", "candle syndrome",
    "carasil syndrome", "carbamoyl phosphate synthetase deficiency",
    "carbohydrate metabolism disorder", "carbonic anhydrase gene mutation",
    "carcinogenic effect in offspring", "card9 deficiency", "cardiac lymphangioma",
    "cardiac malposition", "cardiac septal defect", "cardiofaciocutaneous syndrome",
    "carney complex", "carnitine palmitoyltransferase deficiency",
    "carnitine-acylcarnitine translocase deficiency", "carpenter syndrome",
    "carpus curvus", "cartilage-hair hypoplasia", "cataract congenital",
    "catel manzke syndrome", "caudal regression syndrome", "cayler cardiofacial syndrome",
    "cbl gene mutation", "cdkl5 deficiency disorder", "cebpa gene mutation",
    "cec syndrome", "central core disease", "central nervous system dermoid tumour",
    "cerebellar dysplasia", "cerebellar hypoplasia", "cerebral arteriovenous malformation haemorrhagic",
    "cerebral atrophy congenital", "cerebral cavernous malformation",
    "cerebral dysgenesis", "cerebral palsy", "cerebrohepatorenal syndrome",
    "cerebrovascular arteriovenous malformation", "cervical auricle",
    "cftr gene mutation", "chaple syndrome", "charge syndrome", "checkpoint kinase 2 gene mutation",
    "chediak-higashi syndrome", "chiari network", "child syndrome",
    "chimerism", "choanal atresia", "choanal stenosis", "cholangiectasis congenital",
    "chondrodysplasia punctata", "chondroectodermal dysplasia", "chordee",
    "chorea-acanthocytosis", "chorioretinal degeneration congenital",
    "choroidal coloboma", "chromosomal deletion", "chromosomal mutation",
    "chronic atrial and intestinal dysrhythmia syndrome", "chronic granulomatous disease",
    "chronic infantile neurological cutaneous and articular syndrome",
    "citrate transporter deficiency", "c-kit gene mutation", "c-kit gene overexpression",
    "cleft lip", "cleft lip and palate", "cleft palate", "cleft uvula",
    "cleidocranial dysostosis", "clinodactyly", "cloacal exstrophy",
    "coagulation factor mutation", "coarctation of the aorta", "cobb syndrome",
    "cockayne's syndrome", "coffin siris syndrome", "coffin-lowry syndrome",
    "cohen syndrome", "collodion baby", "coloboma", "colour blindness",
    "combined immunodeficiency", "complement deficiency disease",
    "cone dystrophy", "cone-rod dystrophy", "confined placental mosaicism",
    "congenital abdominal hernia", "congenital absence of bile ducts",
    "congenital absence of cranial vault", "congenital absence of vertebra",
    "congenital acrochordon", "congenital adrenal gland hypoplasia",
    "congenital alopecia", "congenital amputation", "congenital anaemia",
    "congenital androgen deficiency", "congenital anisocoria", "congenital anomalies of ear ossicles",
    "congenital anomaly", "congenital anomaly in offspring", "congenital anomaly of adrenal gland",
    "congenital anomaly of inner ear", "congenital anosmia", "congenital aortic anomaly",
    "congenital aortic atresia", "congenital aortic dilatation",
    "congenital aortic stenosis", "congenital aortic valve incompetence",
    "congenital aortic valve stenosis", "congenital aplastic anaemia",
    "congenital aqueductal stenosis", "congenital arachnoid cyst",
    "congenital arterial malformation", "congenital arterial occlusion",
    "congenital arteriovenous fistula", "congenital astigmatism",
    "congenital aural fistula", "congenital benign neoplasm", "congenital bilateral perisylvian syndrome",
    "congenital bladder anomaly", "congenital bladder diverticulum",
    "congenital bladder neck obstruction", "congenital bowing of long bones",
    "congenital brain damage", "congenital bronchiectasis", "congenital bronchomalacia",
    "congenital calyceal diverticulum", "congenital cardiovascular anomaly",
    "congenital carnitine deficiency", "congenital central diabetes insipidus",
    "congenital central hypoventilation syndrome", "congenital central nervous system anomaly",
    "congenital cerebellar agenesis", "congenital cerebral cyst",
    "congenital cerebral haemangioma", "congenital cerebrovascular anomaly",
    "congenital chagas disease", "congenital choroid plexus cyst",
    "congenital choroidal anomaly", "congenital chylothorax", "congenital clavicular agenesis",
    "congenital claw toe", "congenital coagulopathy", "congenital condyloma",
    "congenital connective tissue disorder", "congenital corneal anomaly",
    "congenital coronary artery malformation", "congenital covid-19",
    "congenital cranial nerve paralysis", "congenital cutis laxa",
    "congenital cyst", "congenital cystic kidney disease", "congenital cystic lung",
    "congenital cytomegalovirus infection", "congenital deformity of clavicle",
    "congenital dengue disease", "congenital dermal sinus", "congenital diaphragmatic anomaly",
    "congenital diaphragmatic eventration", "congenital diaphragmatic hernia",
    "congenital disorder of glycosylation", "congenital dyserythropoietic anaemia",
    "congenital dysfibrinogenaemia", "congenital dyskeratosis", "congenital ebola virus infection",
    "congenital ectodermal dysplasia", "congenital ectopic bladder",
    "congenital ectopic pancreas", "congenital elevation of scapula",
    "congenital emphysema", "congenital endocrine anomaly", "congenital epiblepharon",
    "congenital epiglottal anomaly", "congenital eustachian tube anomaly",
    "congenital eye disorder", "congenital eye naevus", "congenital eyelid malformation",
    "congenital facial nerve hypoplasia", "congenital fallopian tube anomaly",
    "congenital female genital tract fistula", "congenital female reproductive tract disorder",
    "congenital fibrosarcoma", "congenital flaccid paralysis", "congenital flat feet",
    "congenital floppy infant", "congenital foot malformation", "congenital gastric anomaly",
    "congenital gastrointestinal vessel anomaly", "congenital generalised lipodystrophy",
    "congenital genital malformation", "congenital genital malformation female",
    "congenital genital malformation male", "congenital genitourinary abnormality",
    "congenital great vessel anomaly", "congenital growth hormone deficiency",
    "congenital haematological disorder", "congenital hair disorder",
    "congenital hand malformation", "congenital hearing disorder",
    "congenital heart valve disorder", "congenital heart valve incompetence",
    "congenital hemiparesis", "congenital hepatic fibrosis", "congenital hepatitis b infection",
    "congenital hepatitis c infection", "congenital hepatobiliary anomaly",
    "congenital hepatomegaly", "congenital herpes simplex infection",
    "congenital hiatus hernia", "congenital high airway obstruction syndrome",
    "congenital hiv infection", "congenital horner's syndrome", "congenital hydrocele renalis",
    "congenital hydrocephalus", "congenital hydronephrosis", "congenital hypercoagulation",
    "congenital hyperextension of knee", "congenital hyperextension of spine",
    "congenital hyperinsulinaemic hypoglycaemia", "congenital hyperthyroidism",
    "congenital hypertrichosis", "congenital hypogammaglobulinaemia",
    "congenital hypogonadotropic hypogonadism", "congenital hypoparathyroidism",
    "congenital hypoplasia of depressor angularis oris muscle", "congenital hypothyroidism",
    "congenital hypotransferrinaemia", "congenital infection", "congenital inguinal hernia",
    "congenital intestinal malformation", "congenital intestinal obstruction",
    "congenital intrinsic factor deficiency", "congenital iris anomaly",
    "congenital jaw malformation", "congenital joint malformation",
    "congenital knee deformity", "congenital knee dislocation", "congenital kyphoscoliosis",
    "congenital labia pudendi adhesions", "congenital lacrimal gland anomaly",
    "congenital lacrimal passage anomaly", "congenital lactase deficiency",
    "congenital large intestinal atresia", "congenital laryngeal malformation",
    "congenital laryngeal stridor", "congenital lenticonus", "congenital leptin deficiency",
    "congenital limb hyperextension", "congenital lip fistula", "congenital lip pits",
    "congenital lumbar syndrome", "congenital lymphatic dysplasia",
    "congenital lymphoedema", "congenital malaria", "congenital malignant neoplasm",
    "congenital megacolon", "congenital megaureter", "congenital melanocytic naevus",
    "congenital melanosis", "congenital methaemoglobinaemia", "congenital midline defect",
    "congenital mitochondrial cytopathy", "congenital mitral valve incompetence",
    "congenital mitral valve stenosis", "congenital monorchidism",
    "congenital multiplex arthrogryposis", "congenital muscle absence",
    "congenital musculoskeletal disorder", "congenital musculoskeletal disorder of head and neck",
    "congenital musculoskeletal disorder of limbs", "congenital musculoskeletal disorder of skull",
    "congenital musculoskeletal disorder of spine", "congenital musculoskeletal disorder of trunk",
    "congenital myasthenic syndrome", "congenital myopathy", "congenital myopia",
    "congenital naevus", "congenital nail disorder", "congenital nasal septum deviation",
    "congenital neoplasm", "congenital nephrogenic diabetes insipidus",
    "congenital nephrotic syndrome", "congenital neurological degeneration",
    "congenital neurological disorder", "congenital neuropathy",
    "congenital night blindness", "congenital nipple anomaly", "congenital nipple inversion",
    "congenital nose malformation", "congenital nystagmus", "congenital oculomotor apraxia",
    "congenital oesophageal anomaly", "congenital oesophageal stenosis",
    "congenital oesophageal web", "congenital optic nerve anomaly",
    "congenital oral malformation", "congenital osteodystrophy",
    "congenital ovarian anomaly", "congenital oxalosis", "congenital pancreatic anomaly",
    "congenital parvovirus b19 infection", "congenital perforated nasal septum",
    "congenital pharyngeal anomaly", "congenital pigmentation disorder",
    "congenital pneumonia", "congenital poikiloderma", "congenital pseudarthrosis",
    "congenital pulmonary artery anomaly", "congenital pulmonary hypertension",
    "congenital pulmonary valve atresia", "congenital pulmonary valve disorder",
    "congenital pyelocaliectasis", "congenital renal cyst", "congenital renal disorder",
    "congenital retinoblastoma", "congenital rubella infection",
    "congenital rubella syndrome", "congenital salivary gland anomaly",
    "congenital scleral disorder", "congenital scoliosis", "congenital scrotal hypertrophy",
    "congenital skin dimples", "congenital skin disorder", "congenital small intestinal atresia",
    "congenital spinal cord anomaly", "congenital spinal fusion",
    "congenital spinal stenosis", "congenital spondylolisthesis",
    "congenital spondylolysis", "congenital subglottic stenosis",
    "congenital supraventricular tachycardia", "congenital syphilis",
    "congenital syphilitic encephalitis", "congenital syphilitic meningitis",
    "congenital syphilitic osteochondritis", "congenital teratoma",
    "congenital thrombocyte disorder", "congenital thrombocytopenia",
    "congenital thymus absence", "congenital thyroid disorder", "congenital tongue anomaly",
    "congenital torticollis", "congenital toxoplasmosis", "congenital tracheomalacia",
    "congenital trichomegaly", "congenital tricuspid valve atresia",
    "congenital tricuspid valve incompetence", "congenital tricuspid valve stenosis",
    "congenital tuberculosis", "congenital umbilical hernia", "congenital ureteric anomaly",
    "congenital ureterocele", "congenital ureteropelvic junction obstruction",
    "congenital ureterovesical junction anomaly", "congenital urethral anomaly",
    "congenital urinary tract obstruction", "congenital uterine anomaly",
    "congenital vaginal cyst", "congenital varicella infection",
    "congenital varicocele", "congenital vas deferens absence", "congenital vena cava stenosis",
    "congenital vesicoureteric reflux", "congenital viral hepatitis",
    "congenital viral infection", "congenital visual acuity reduced",
    "congenital vitreous anomaly", "congenital vocal cord paralysis",
    "congenital white blood cell disorder", "congenital zika syndrome",
    "conjoined twins", "conjunctivitis gonococcal neonatal", "connective tissue dysplasia",
    "constricted ear deformity", "copa syndrome", "cor biloculare",
    "cor triatriatum", "corneal dystrophy", "corneal opacity congenital",
    "cornelia de lange syndrome", "corrected transposition of great vessels",
    "cortical dysplasia", "costello syndrome", "cowden's disease",
    "craniofacial deformity", "craniofacial dysostosis", "craniolacunia",
    "craniorachischisis", "craniosynostosis", "craniotabes", "creatine deficiency syndrome",
    "cri du chat syndrome", "cria syndrome", "crigler-najjar syndrome",
    "cryopyrin associated periodic syndrome", "cryptophthalmos",
    "cryptorchism", "cryptotia", "ctla4 deficiency", "currarino syndrome",
    "cutaneovisceral angiomatosis with thrombocytopenia", "cyclopia",
    "cyp1a2 polymorphism", "cyp2b6 polymorphism", "cyp2c19 polymorphism",
    "cyp2c9 polymorphism", "cyp2d6 polymorphism", "cyp3a4 polymorphism",
    "cyp3a5 polymorphism", "cystathionine beta-synthase deficiency",
    "cystic angiomatosis", "cystic eyeball, congenital", "cystic fibrosis",
    "cystic fibrosis carrier", "cystic fibrosis gastrointestinal disease",
    "cystic fibrosis hepatic disease", "cystic fibrosis lung", "cystic fibrosis pancreatic",
    "cystic fibrosis related diabetes", "cystic lymphangioma", "cystinosis",
    "cystinuria", "cytogenetic abnormality", "dacryocystocoele",
    "dacryostenosis congenital", "dandy-walker syndrome", "ddx3x syndrome",
    "de barsy syndrome", "de la chapelle syndrome", "deaf mutism",
    "deafness congenital", "deficiency of the interleukin-1 receptor antagonist",
    "deficiency of the interleukin-36 receptor antagonist", "delayed foetal renal development",
    "delta-beta thalassaemia", "dentatorubral-pallidoluysian atrophy",
    "dentofacial anomaly", "dent's disease", "denys-drash syndrome",
    "dermatofibrosis lenticularis disseminata", "dermatoglyphic anomaly",
    "dermoid cyst", "desmin myopathy", "developmental glaucoma",
    "developmental hip dysplasia", "dextrocardia", "diabetic foetopathy",
    "diaphragmatic aplasia", "diastematomyelia", "diastrophic dysplasia",
    "diencephalic syndrome of infancy", "diethylstilboestrol syndrome",
    "digeorge's syndrome", "dihydropyrimidine dehydrogenase deficiency",
    "dilatation intrahepatic duct congenital", "disorder of sex development",
    "disseminated neonatal herpes simplex", "disseminated superficial actinic porokeratosis",
    "distichiasis", "diverticulitis meckel's", "diverticulum of pharynx, congenital",
    "dna mismatch repair protein gene mutation", "dnmt3a gene mutation",
    "dolichocephaly", "dolichocolon", "donohue syndrome", "door syndrome",
    "dopa-responsive dystonia", "double cortex syndrome", "double heterozygous sickling disorders",
    "double inlet left ventricle", "double outlet left ventricle",
    "double outlet right ventricle", "double ureter", "dowling-degos disease",
    "duane's syndrome", "dubin-johnson syndrome", "dubowitz syndrome",
    "duchenne muscular dystrophy", "duchenne muscular dystrophy gene carrier",
    "ductus arteriosus premature closure", "ductus arteriosus stenosis foetal",
    "ductus venosus agenesis", "duodenal atresia", "duplex appendix",
    "duplication of inferior vena cava", "dyke-davidoff-masson syndrome",
    "dyschondrosteosis", "dyschromatosis", "dysgnathia", "dysmorphism",
    "dysmyelination", "dysplastic naevus syndrome", "eagle barrett syndrome",
    "ear malformation", "early onset familial alzheimer's disease",
    "early onset primary dystonia", "ebstein's anomaly", "ectonucleotide pyrophosphatase/phosphodiesterase 1 deficiency",
    "ectopia cordis", "ectopic kidney", "ectopic ovary", "ectopic posterior pituitary gland",
    "ectopic thyroid", "ectopic ureter", "ectrodactyly", "egfr gene mutation",
    "egfr gene overexpression", "ehlers-danlos syndrome", "elbow synostosis",
    "elliptocytosis hereditary", "ellis-van creveld syndrome", "emanuel syndrome",
    "emery-dreifuss muscular dystrophy", "encephalocele", "encephalocutaneous angiomatosis",
    "endocardial fibroelastosis", "endothelial protein c receptor polymorphism",
    "enteric duplication", "entropion congenital", "epidermal naevus",
    "epidermal naevus syndrome", "epidermolysis", "epidermolysis bullosa",
    "epilepsy congenital", "epilepsy of infancy with migrating focal seizures",
    "epilepsy with myoclonic-atonic seizures", "epispadias", "erythroblastosis foetalis",
    "erythrokeratodermia variabilis", "essential fructosuria", "exomphalos",
    "exophthalmos congenital", "external auditory canal atresia",
    "extrarenal pelvis", "eye anterior chamber congenital anomaly",
    "eyelid ptosis congenital", "ezh2 gene mutation", "fabry's disease",
    "faciodigitogenital dysplasia", "facioscapulohumeral muscular dystrophy",
    "factor i deficiency", "factor ii deficiency", "factor ii mutation",
    "factor iii deficiency", "factor ix deficiency", "factor v deficiency",
    "factor v leiden mutation", "factor vii deficiency", "factor viii deficiency",
    "factor x deficiency", "factor xi deficiency", "factor xii deficiency",
    "factor xiii deficiency", "fallot's pentalogy", "fallot's tetralogy",
    "fallot's trilogy", "familial acromegaly", "familial amyloidosis",
    "familial amyotrophic lateral sclerosis", "familial chondrocalcinosis",
    "familial cold autoinflammatory syndrome", "familial gigantiform cementoma",
    "familial glucocorticoid deficiency", "familial haemophagocytic lymphohistiocytosis",
    "familial hemiplegic migraine", "familial high density lipoprotein deficiency",
    "familial hypertriglyceridaemia", "familial hypocalciuric hypercalcaemia",
    "familial infantile bilateral striatal necrosis", "familial isolated hyperparathyroidism",
    "familial mediterranean fever", "familial medullary thyroid cancer",
    "familial multiple lipomatosis", "familial partial lipodystrophy",
    "familial periodic paralysis", "familial polycythaemia", "familial renal glycosuria",
    "familial scaphocephaly syndrome", "familial tremor", "fanconi syndrome",
    "fatal familial insomnia", "fatty acid oxidation disorder", "femoral anteversion",
    "femoral facial syndrome", "femoral retroversion", "femur-fibula-ulna complex",
    "fibrodysplasia ossificans progressiva", "fibromatosis colli of infancy",
    "fibrous dysplasia of bone", "fibrous dysplasia of jaw", "fibula agenesis",
    "filippi syndrome", "fissure of tongue, congenital", "floating-harbor syndrome",
    "flt3 gene mutation", "foetal alcohol syndrome", "foetal anticonvulsant syndrome",
    "foetal chromosome abnormality", "foetal cystic hygroma", "foetal malformation",
    "foetal megacystis", "foetal methotrexate syndrome", "foetal retinoid syndrome",
    "foetal tobacco syndrome", "foetal warfarin syndrome", "foramen magnum stenosis",
    "fountain syndrome", "fragile x carrier", "fragile x syndrome",
    "fraser syndrome", "frasier syndrome", "freeman-sheldon syndrome",
    "frenulum breve", "friedreich's ataxia", "fructose-1,6-bisphosphatase deficiency",
    "fryns syndrome", "galactosaemia", "galactosialidosis", "gallbladder agenesis",
    "gallbladder anomaly congenital", "gap junction protein beta 2 gene mutation",
    "gastrointestinal arteriovenous malformation", "gastrointestinal disorder congenital",
    "gastrointestinal malformation", "gastroschisis", "gata2 deficiency",
    "gatad2b associated neurodevelopmental disorder", "gaucher's disease",
    "gaucher's disease type i", "gaucher's disease type ii", "gaucher's disease type iii",
    "gene mutation", "generalised resistance to thyroid hormone",
    "genetic polymorphism", "geniospasm", "genitalia external ambiguous",
    "gilbert's syndrome", "gitelman's syndrome", "glanzmann's disease",
    "glucose transporter type 1 deficiency syndrome", "glucose-6-phosphate dehydrogenase deficiency",
    "glucose-galactose malabsorption", "glutathione synthetase deficiency",
    "glycogen storage disease type i", "glycogen storage disease type ii",
    "glycogen storage disease type iii", "glycogen storage disease type iv",
    "glycogen storage disease type ix", "glycogen storage disease type v",
    "glycogen storage disease type vi", "glycogen storage disease type vii",
    "glycogen storage disease type viii", "glycogen storage disorder",
    "glycoprotein metabolism disorder", "gm2 gangliosidosis", "gnathoschisis",
    "gne myopathy", "goitre congenital", "gollop-wolfgang complex",
    "gonadal dysgenesis", "gorham's disease", "gracile syndrome",
    "greig's syndrome", "grey matter heterotopia", "griscelli syndrome",
    "haemangioma congenital", "haemangioma of retina", "haemochromatosis carrier",
    "haemochromatosis trait", "haemoglobin c disease", "haemoglobin c trait",
    "haemoglobin d disease", "haemoglobin d trait", "haemoglobin e disease",
    "haemoglobin e trait", "haemoglobin e-thalassaemia disease",
    "haemoglobin lepore trait", "haemoglobinopathy", "haemophilia",
    "haemophilia a with anti factor viii", "haemophilia a without inhibitors",
    "haemophilia b with anti factor ix", "haemophilia b without inhibitors",
    "haemophilia carrier", "haemorrhagic arteriovenous malformation",
    "hamartoma", "hamartoma vascular", "hand-foot-genital syndrome",
    "harlequin foetus", "hartnup disease", "heart block congenital",
    "heart disease congenital", "hemihypertrophy", "hemimegalencephaly",
    "hemivertebra", "heparin cofactor ii deficiency", "hepatic arteriovenous malformation",
    "hepatic hamartoma", "hepato-lenticular degeneration", "her2 gene amplification",
    "her2 protein overexpression", "hereditary angioedema", "hereditary angioedema with c1 esterase inhibitor deficiency",
    "hereditary angioedema with normal c1 esterase inhibitor", "hereditary areflexic dystasia",
    "hereditary ataxia", "hereditary cerebral degeneration", "hereditary choroidal dystrophy",
    "hereditary disorder", "hereditary fructose intolerance", "hereditary haemochromatosis",
    "hereditary haemolytic anaemia", "hereditary haemorrhagic telangiectasia",
    "hereditary hypophosphataemic rickets", "hereditary leiomyomatosis renal cell carcinoma",
    "hereditary microcytic anaemia", "hereditary motor and sensory neuropathy",
    "hereditary motor neurone disease", "hereditary multiple osteochondromas",
    "hereditary neuropathic amyloidosis", "hereditary neuropathy with liability to pressure palsies",
    "hereditary non-polyposis colorectal cancer syndrome", "hereditary optic atrophy",
    "hereditary palmoplantar keratoderma", "hereditary pancreatitis",
    "hereditary papillary renal carcinoma", "hereditary persistence of foetal haemoglobin",
    "hereditary renal microhaematuria", "hereditary retinal dystrophy",
    "hereditary sideroblastic anaemia", "hereditary spastic paraplegia",
    "hereditary spherocytosis", "hereditary stomatocytosis", "herg gene mutation",
    "heritable pulmonary arterial hypertension", "hermansky-pudlak syndrome",
    "hermaphroditism", "hernia congenital", "heterochromia iridis",
    "heterotaxia", "hexokinase deficiency anaemia", "high arched palate",
    "histiocytosis-lymphadenopathy plus syndrome", "hollow visceral myopathy",
    "holoprosencephaly", "holt-oram syndrome", "homocystinaemia",
    "homocystinuria", "hooded prepuce", "h-ras gene mutation", "huntington's disease",
    "hydranencephaly", "hydrocele", "hydroxyprolinaemia", "hyper igd syndrome",
    "hyper ige syndrome", "hyper igm syndrome", "hyperexplexia",
    "hyperglycinaemia", "hyperlysinaemia", "hypermethioninaemia",
    "hypermethioniuria", "hypermutation", "hyperornithinaemia-hyperammonaemia-homocitrullinuria syndrome",
    "hyperphenylalaninaemia", "hyperpipecolic acidaemia", "hyperprolinaemia",
    "hypersplenism congenital", "hypertelorism", "hypertrophic cardiomyopathy",
    "hypocalvaria", "hypochondroplasia", "hypodontia", "hypomelanosis of ito",
    "hypophosphatasia", "hypopituitarism foetal", "hypoplastic left heart syndrome",
    "hypoplastic nasal cartilage", "hypoplastic right heart syndrome",
    "hypospadias", "hypotelorism of orbit", "hypothalamic hamartoma",
    "hypotonia-cystinuria syndrome", "hypoxanthine-guanine phosphoribosyl transferase deficiency",
    "ichthyosis", "ileal atresia", "immunodeficiency congenital",
    "imperforate hymen", "imperforate oesophagus", "inborn error in primary bile acid synthesis",
    "inborn error of amino acid metabolism", "inborn error of bilirubin metabolism",
    "inborn error of lipid metabolism", "inborn error of metabolism",
    "inborn error of steroid synthesis", "infantile cortical hyperostosis",
    "infantile fibromatosis", "infantile genetic agranulocytosis",
    "infantile septic granulomatosis", "inherited cardiac conduction disorder",
    "inherited otosclerosis", "iniencephaly", "interferon gamma receptor deficiency",
    "interleukin 28b polymorphism", "interruption of aortic arch",
    "intestinal atresia", "intestinal malrotation", "intestinal neuronal dysplasia",
    "intestinal transposition", "intracranial arterial fenestration",
    "intracranial lipoma", "ipex syndrome", "iris coloboma", "iris hamartoma",
    "isocitrate dehydrogenase gene mutation", "isodicentric chromosome 15 syndrome",
    "isovaleric acidaemia", "jag1 gene mutation", "janus kinase 2 mutation",
    "johanson-blizzard syndrome", "joubert syndrome", "juvenile paget's disease",
    "kabuki make-up syndrome", "kaufman-mckusick syndrome", "kbg syndrome",
    "kearns-sayre syndrome", "kenny-caffey syndrome", "keratitis-ichthyosis-deafness syndrome",
    "keratolysis exfoliativa congenital", "keratosis follicular",
    "kidney duplex", "kidney malformation", "kidney malrotation",
    "kimmerle's anomaly", "kinematic imbalances due to suboccipital strain",
    "kleefstra syndrome", "klinefelter's syndrome", "klippel-feil syndrome",
    "klippel-trenaunay syndrome", "kmt2a gene mutation", "kniest dysplasia",
    "kommerell's diverticulum", "kosaki overgrowth syndrome", "krabbe's disease",
    "k-ras gene mutation", "kyphosis congenital", "laband syndrome",
    "labial tie", "labrune syndrome", "lacrimal punctum agenesis",
    "lacrimo-auriculo-dento-digital syndrome", "laevocardia", "lafora's myoclonic epilepsy",
    "lamin a/c gene mutation", "langer-giedion syndrome", "laron syndrome",
    "larsen syndrome", "laryngeal cleft", "laryngeal web", "laryngocele",
    "laryngomalacia", "laryngo-onycho-cutaneous syndrome", "laurence-moon-bardet-biedl syndrome",
    "ldlr mutation", "leber's congenital amaurosis", "lecithin-cholesterol acyltransferase deficiency",
    "left ventricle outflow tract obstruction", "left ventricular false tendon",
    "left-to-right cardiac shunt", "lens abnormality, congenital",
    "leptin receptor deficiency", "leukocyte adhesion deficiency type i",
    "leukodystrophy", "lichen spinulosus", "liddle's syndrome", "li-fraumeni syndrome",
    "limb hypoplasia congenital", "limb reduction defect", "lipid proteinosis",
    "lipidosis", "lipodermoid tumour", "lipomeningocele", "lissencephaly",
    "loeys-dietz syndrome", "long qt syndrome congenital", "long-chain acyl-coenzyme a dehydrogenase deficiency",
    "loose anagen syndrome", "low set ears", "lown-ganong-levine syndrome",
    "lowry-wood syndrome", "lumbarisation", "lymphangiectasia intestinal congenital",
    "lysinuric protein intolerance", "lysosomal acid lipase deficiency",
    "lysosomal storage disorder", "macrocephaly", "macrocheilia",
    "macrocornea", "macrodactyly", "macrogenia", "macroglossia",
    "macrognathia", "macrophthalmos", "macrostomia", "macrotia",
    "macular dystrophy congenital", "majeed's syndrome", "malformation biliary",
    "malformation venous", "mandibulofacial dysostosis", "mannose-binding lectin deficiency",
    "maple syrup disease", "marcus gunn syndrome", "marfan's syndrome",
    "maternally inherited diabetes and deafness", "maxillonasal dysplasia",
    "mayer-rokitansky-kuster-hauser syndrome", "mazabraud's syndrome",
    "mcleod neuroacanthocytosis syndrome", "medium-chain acyl-coenzyme a dehydrogenase deficiency",
    "meier-gorlin syndrome", "melanocortin 4 receptor deficiency",
    "melas syndrome", "melkersson-rosenthal syndrome", "membranous lipodystrophy",
    "meningocele", "meningomyelocele", "menkes' syndrome", "mesoblastic nephroma",
    "mesonephric duct cyst", "metabolic myopathy", "metachromatic leukodystrophy",
    "metaphyseal dysplasia", "metatarsus primus varus", "metatropic dysplasia",
    "methylenetetrahydrofolate reductase deficiency", "methylenetetrahydrofolate reductase gene mutation",
    "methylenetetrahydrofolate reductase polymorphism", "methylmalonic aciduria",
    "mevalonate kinase deficiency", "mevalonic aciduria", "microcephaly",
    "microcheilia", "microcolon", "microcornea", "microencephaly",
    "microgenia", "microglossia", "micrognathia", "microorchidism",
    "micropenis", "microphthalmos", "microstomia", "microtia", "microvillous inclusion disease",
    "mismatch repair cancer syndrome", "mitochondrial cardiomyopathy",
    "mitochondrial dna deletion", "mitochondrial dna depletion",
    "mitochondrial dna duplication", "mitochondrial dna mutation",
    "mitochondrial encephalomyopathy", "mitochondrial enzyme deficiency",
    "mitochondrial hepatopathy", "mitochondrial myopathy", "mitochondrial neurogastrointestinal encephalopathy",
    "mitral valve atresia", "mitral valve hypoplasia", "mittendorf dot",
    "mlasa syndrome", "mobile caecum syndrome", "moebius ii syndrome",
    "molybdenum cofactor deficiency", "monolid eyes", "monopodia",
    "morgagni-stewart-morel syndrome", "morning glory syndrome",
    "morton's syndrome", "mosaicism", "mount-reback syndrome", "mpl gene mutation",
    "muckle-wells syndrome", "mucolipidosis", "mucolipidosis type i",
    "mucolipidosis type ii", "mucolipidosis type iii", "mucolipidosis type iv",
    "mucopolysaccharidosis", "mucopolysaccharidosis i", "mucopolysaccharidosis ii",
    "mucopolysaccharidosis iii", "mucopolysaccharidosis iv", "mucopolysaccharidosis ix",
    "mucopolysaccharidosis v", "mucopolysaccharidosis vi", "mucopolysaccharidosis vii",
    "muir-torre syndrome", "multiple carboxylase deficiency", "multiple cardiac defects",
    "multiple congenital abnormalities", "multiple cutaneous and uterine leiomyomatosis",
    "multiple endocrine neoplasia", "multiple endocrine neoplasia type 1",
    "multiple endocrine neoplasia type 2", "multiple endocrine neoplasia type 2a",
    "multiple endocrine neoplasia type 2b", "multiple epiphyseal dysplasia",
    "multiple gastrointestinal atresias", "multiple lentigines syndrome",
    "muscular dystrophy", "mutagenic effect", "myeloperoxidase deficiency",
    "myh9-related disease", "myocardial bridging", "myoclonic dystonia",
    "myoclonic epilepsy and ragged-red fibres", "myofibrillar myopathy",
    "myotonia congenita", "myotonic dystrophy", "n-acetylglutamate synthase deficiency",
    "naevus anaemicus", "naevus flammeus", "naevus spider congenital",
    "nager syndrome", "nail aplasia", "nail-patella syndrome", "nasopharyngeal atresia",
    "nat1 polymorphism", "nat2 polymorphism", "neonatal alloimmune thrombocytopenia",
    "neonatal haemochromatosis", "neonatal leukaemia", "neonatal lupus erythematosus",
    "netherton's syndrome", "neural tube defect", "neuroacanthocytosis",
    "neurodegeneration with brain iron accumulation disorder", "neurofibromatosis",
    "neuronal ceroid lipofuscinosis", "neuronal migration disorder",
    "neuropathy, ataxia, retinitis pigmentosa syndrome", "neutrophil fc gamma riiib deficiency",
    "newborn persistent pulmonary hypertension", "niemann-pick disease",
    "nievergelt-pearlman syndrome", "nijmegen breakage syndrome",
    "non-compaction cardiomyopathy", "noonan syndrome", "norrie's disease",
    "npm1 gene mutation", "nr5a1 gene mutation", "n-ras gene mutation",
    "ntrk gene fusion overexpression", "nut gene mutation", "ocular albinism",
    "oculoauriculovertebral dysplasia", "oculocerebrorenal syndrome",
    "oculodentodigital dysplasia", "oculo-digito-oesophageal-duodenal syndrome",
    "oculopharyngeal dystrophy", "odontogenic cyst", "odontoma",
    "oesophageal atresia", "oesophageal cyst", "oestrogen receptor gene overexpression",
    "ogden syndrome", "ohvira syndrome", "olfacto genital dysplasia",
    "olfactory nerve agenesis", "olmsted syndrome", "omenn syndrome",
    "opitz trigonocephaly syndrome", "opitz-g/bbb syndrome", "optic disc pit",
    "optic nerve hypoplasia", "oral-facial-digital syndrome type ii",
    "ornithine transcarbamoylase deficiency", "oroticaciduria congenital",
    "os trigonum", "osteochondrodysplasia", "osteogenesis imperfecta",
    "osteopathia striata", "osteopetrosis", "osteopoikilosis", "osteoporosis-pseudoglioma syndrome",
    "ota's naevus", "otocephaly", "otopalatodigital spectrum disorder",
    "otospondylomegaepiphyseal dysplasia", "ovarian agenesis", "ovarian hypoplasia",
    "oxycephaly", "pachydermoperiostosis", "pachygyria", "pachyonychia congenita",
    "pallister w syndrome", "pallister-killian syndrome", "pancreas divisum",
    "papillon-lefevre syndrome", "papss2 gene mutation", "parachute mitral valve",
    "paranasal sinus aplasia", "paranasal sinus hypoplasia", "parkes-weber syndrome",
    "paroxysmal extreme pain disorder", "patent ductus arteriosus",
    "pearson's syndrome", "pectus carinatum", "pectus excavatum",
    "pelizaeus-merzbacher disease", "pelvic kidney", "pendred syndrome",
    "penile torsion", "penoscrotal fusion", "penoscrotal transposition",
    "penta x syndrome", "periodontal congenital anomaly", "perry syndrome",
    "persistent cloaca", "persistent foetal circulation", "persistent left superior vena cava",
    "persistent muellerian duct syndrome", "persistent pupillary membrane",
    "persistent urogenital sinus", "peutz-jeghers syndrome", "pfeiffer syndrome",
    "phaces syndrome", "phakomatosis", "phalangeal agenesis", "phalangeal hypoplasia",
    "phelan-mcdermid syndrome", "phenylketonuria", "phimosis", "phytosterolaemia",
    "piebaldism", "pik3ca related overgrowth spectrum", "pik3ca-activated mutation",
    "pilonidal cyst congenital", "plagiocephaly", "plasminogen activator inhibitor polymorphism",
    "plasminogen activator inhibitor type 1 deficiency", "platelet glycoprotein gene mutation",
    "platelet storage pool deficiency", "platelet-derived growth factor receptor gene mutation",
    "platelet-derived growth factor receptor overexpression", "platonychia",
    "platybasia", "platyspondylia", "pleural malformation", "poland's syndrome",
    "polycystic liver disease", "polydactyly", "polymicrogyria",
    "polyorchidism", "popliteal pterygium syndrome", "porencephaly",
    "porokeratosis", "porphyria", "porphyria acute", "porphyria non-acute",
    "porphyrin metabolism disorder", "porphyrinuria", "portal venous system anomaly",
    "postauricular fistula", "posterior segment of eye anomaly congenital",
    "potter's syndrome", "prader-willi syndrome", "preauricular cyst",
    "preduodenal portal vein", "preternatural anus", "primary bilateral macronodular adrenal hyperplasia",
    "primary cerebellar degeneration", "primary ciliary dyskinesia",
    "primary coenzyme q10 deficiency", "primary familial brain calcification",
    "primary familial hypomagnesaemia", "primary hypercholesterolaemia",
    "primary hyperoxaluria", "primary immunodeficiency syndrome",
    "primary insulin like growth factor-1 deficiency", "progeria",
    "progesterone receptor gene overexpression", "progressive cerebellar degeneration",
    "progressive diaphyseal dysplasia", "progressive encephalopathy, hypsarrhythmia and optic atrophy syndrome",
    "progressive external ophthalmoplegia", "progressive familial intrahepatic cholestasis",
    "prominent epicanthal folds", "pro-opiomelanocortin deficiency",
    "protein c deficiency", "protein s deficiency", "proteus syndrome",
    "protuberant ear", "proximal focal femoral deficiency", "prpf8 gene mutation",
    "pseudocholinesterase deficiency", "pseudohermaphroditism", "pseudohermaphroditism female",
    "pseudohermaphroditism male", "pseudohypoaldosteronism", "pseudohypoparathyroidism",
    "pseudotruncus arteriosus", "pseudoxanthoma elasticum", "pstpip1-associated myeloid-related proteinaemia inflammatory syndrome",
    "pten gene mutation", "pterygium colli", "ptpn11 gene mutation",
    "pulmonary aplasia", "pulmonary arteriovenous fistula", "pulmonary artery atresia",
    "pulmonary artery stenosis congenital", "pulmonary hypoplasia",
    "pulmonary lymphangiectasia", "pulmonary malformation", "pulmonary sequestration",
    "pulmonary valve stenosis congenital", "pura syndrome", "purine nucleoside phosphorylase deficiency",
    "pycnodysostosis", "pyloric stenosis", "pyogenic sterile arthritis pyoderma gangrenosum and acne syndrome",
    "pyruvate carboxylase deficiency", "pyruvate dehydrogenase complex deficiency",
    "pyruvate kinase deficiency anaemia", "rapid-onset dystonia-parkinsonism",
    "rathke's cleft cyst", "rectal atresia", "red blood cell enzymes abnormal",
    "refsum's disease", "renal aplasia", "renal arteriovenous malformation",
    "renal dysplasia", "renal fusion anomaly", "renal hypoplasia",
    "renal malposition", "renal vessel congenital anomaly", "reproductive tract hypoplasia, male",
    "respiratory tract malformation", "ret gene mutation", "retinal anomaly congenital",
    "retinal arteriovenous malformation", "retinal coloboma", "retinitis pigmentosa",
    "retinopathy congenital", "retinoschisis congenital", "rett syndrome",
    "rhesus haemolytic disease of newborn", "rib hypoplasia", "rib synostosis",
    "riedel lobe", "right aortic arch", "right ventricle outflow tract obstruction",
    "right ventricular false tendon", "right-to-left cardiac shunt",
    "riley-day syndrome", "ring chromosome", "rippling muscle disease",
    "roberts syndrome", "robinow syndrome", "ros1 gene rearrangement",
    "rotor's syndrome", "rpe65 gene mutation", "rubinstein-taybi syndrome",
    "runx1 gene mutation", "sacral hypoplasia", "sacralisation",
    "saddan syndrome", "saposin c deficiency", "sarcoglycanopathy",
    "sarcosinaemia", "satb2-associated syndrome", "scaphocephaly",
    "schimke immunoosseous dysplasia", "schinzel syndrome", "schinzel-giedion syndrome",
    "schizencephaly", "schmid fraccaro syndrome", "schwartz jampel syndrome",
    "scimitar syndrome", "sclerotylosis", "sebaceous naevus", "senior-loken syndrome",
    "sensory neuropathy hereditary", "septate hymen", "septo-optic dysplasia",
    "septum pellucidum agenesis", "sertoli-cell-only syndrome", "severe myoclonic epilepsy of infancy",
    "severe primary insulin like growth factor-1 deficiency", "sex chromosome abnormality",
    "sf3b1 gene mutation", "shawl scrotum", "shone complex", "short stature homeobox gene mutation",
    "short-chain acyl-coenzyme a dehydrogenase deficiency", "shprintzen-goldberg syndrome",
    "shwachman-diamond syndrome", "sickle cell anaemia", "sickle cell disease",
    "sickle cell trait", "silver-russell syndrome", "simpson-golabi-behmel syndrome",
    "single atrium", "single umbilical artery", "sirenomelia", "sjogren-larsson syndrome",
    "skeletal dysplasia", "skin hypoplasia", "skin malformation",
    "small patella syndrome", "smith-lemli-opitz syndrome", "smith-magenis syndrome",
    "sotos' syndrome", "special senses congenital anomaly", "spherophakia",
    "spina bifida", "spina bifida cystica", "spina bifida occulta",
    "spinal muscular atrophy", "spinal vessel congenital anomaly",
    "spleen malformation", "splenic hamartoma", "split hand nystagmus syndrome",
    "spondyloepiphyseal dysplasia", "srsf2 gene mutation", "stag2 gene mutation",
    "stahl's ear", "stargardt's disease", "steatocystoma multiplex",
    "stickler's syndrome", "sticky platelet syndrome", "stiff skin syndrome",
    "strabismus congenital", "straddling tricuspid valve", "sturge-weber syndrome",
    "sucrase-isomaltase deficiency", "supernumerary nipple", "supernumerary rib",
    "supernumerary teeth", "supernumerary vertebra", "swyer syndrome",
    "syndactyly", "synostosis", "syringomyelia", "systemic right ventricle",
    "talipes", "tangier disease", "telangiectasia congenital", "teratogenicity",
    "testicular dysplasia", "testotoxicosis", "tet2 gene mutation",
    "tetrahydrobiopterin deficiency", "thalassaemia", "thalassaemia alpha",
    "thalassaemia beta", "thalassaemia minor", "thalassaemia sickle cell",
    "thalidomide embryopathy", "thanatophoric dwarfism", "thiopurine methyltransferase polymorphism",
    "thrombocytopenia-absent radius syndrome", "thymus hypoplasia",
    "thyroglossal cyst", "thyroglossal fistula", "thyroid hemiagenesis",
    "thyroid malformation", "tibial agenesis", "tibial torsion",
    "tilted disc syndrome", "timothy syndrome", "tooth discolouration congenital",
    "tooth hypoplasia", "tooth malformation hereditary", "torch infection",
    "tornwaldt cyst", "tourette's disorder", "tp53 gene mutation",
    "tracheal atresia", "tracheal web", "tracheobronchomegaly", "tracheo-oesophageal fistula",
    "transcobalamin deficiency", "transgenerational epigenetic inheritance",
    "transitional vertebrae", "transmembrane receptor tyrosine kinase overexpression",
    "transposition of the great vessels", "trichorhinophalangeal syndrome",
    "trifunctional protein deficiency", "trimethylaminuria", "triple a syndrome",
    "trisomy 11", "trisomy 12", "trisomy 13", "trisomy 14", "trisomy 15",
    "trisomy 16", "trisomy 17", "trisomy 18", "trisomy 21", "trisomy 22",
    "trisomy 4p", "trisomy 8", "trisomy 9", "trpv4 gene mutation",
    "truncus arteriosus persistent", "tuberous sclerosis complex",
    "tumour necrosis factor receptor-associated periodic syndrome",
    "turner's syndrome", "twin reversed arterial perfusion sequence malformation",
    "tympanomeningeal fissure", "type i hyperlipidaemia", "type ii hyperlipidaemia",
    "type iia hyperlipidaemia", "type iib hyperlipidaemia", "type iii hyperlipidaemia",
    "type iv hyperlipidaemia", "type v hyperlipidaemia", "tyrosinaemia",
    "tyrosine kinase mutation", "u2af1 gene mutation", "ugt1a1 gene mutation",
    "ugt1a1 gene polymorphism", "uhl's anomaly", "umbilical artery hypoplasia",
    "umbilical malformation", "unicuspid aortic valve", "univentricular heart",
    "urachal abnormality", "urea cycle disorder", "ureteric atresia",
    "urethral atresia", "urethral valves", "urinary tract malformation",
    "usher's syndrome", "uterine aplasia", "uterine cervix canal atresia",
    "uterine cervix hypoplasia", "uterine hypoplasia", "uvula aplasia",
    "vacterl syndrome", "vaginal atresia", "vaginal hypoplasia",
    "vaginal septum", "vallecular cyst", "vascular endothelial growth factor overexpression",
    "vascular malformation", "vein of galen aneurysmal malformation",
    "velo-cardio-facial syndrome", "venolymphatic malformation",
    "venous angioma of brain", "ventricular hypoplasia", "ventricular septal defect",
    "vertebral artery hypoplasia", "vertical talus", "very long-chain acyl-coenzyme a dehydrogenase deficiency",
    "vestibulocerebellar syndrome", "vexas syndrome", "virilism foetal",
    "vitello-intestinal duct remnant", "vkorc1 gene polymorphism",
    "von hippel-lindau disease", "von willebrand's disease", "von willebrand's disease gene carrier",
    "waardenburg syndrome", "wagner's disease", "weaver syndrome",
    "weill-marchesani syndrome", "welander distal myopathy", "werner's syndrome",
    "wildervanck syndrome", "williams syndrome", "winchester syndrome",
    "wiskott-aldrich syndrome", "wolff-parkinson-white syndrome congenital",
    "wolf-hirschhorn syndrome", "wolfram syndrome", "woodhouse-sakati syndrome",
    "wt1 gene mutation", "wyburn mason's syndrome", "xeroderma pigmentosum",
    "x-linked chromosomal disorder", "x-linked intellectual disability, siderius type",
    "x-linked lymphoproliferative syndrome", "xxx syndrome", "xxxy syndrome",
    "xxyy syndrome", "xyy syndrome", "y-linked chromosomal disorder",
    "young's syndrome", "zeichi-ceide syndrome", "zhu-tokita-takenouchi-kim syndrome",
    "zika virus associated birth defect", "zika virus associated microencephaly",
    "zika virus associated ocular birth defect", "zrsr2 gene mutation"
  )

  ## pregnancy reaction -------------------
  pregnancy_reaction <- unique(c(
    pregnancy_indication, child_def, "acne infantile", "administration site reaction neonatal",
    "adrenocortical insufficiency neonatal", "agitation neonatal",
    "anaemia neonatal", "anaesthetic complication neonatal", "aorticopulmonary window repair",
    "apgar score abnormal", "apgar score low", "arrhythmia neonatal",
    "arterial switch operation", "atelectasis neonatal", "atrial septal defect repair",
    "atrial switch operation", "balloon atrial septostomy", "birth defect correction",
    "birth trauma", "blood loss anaemia neonatal", "bradycardia neonatal",
    "breast engorgement in newborn", "bronchopulmonary dysplasia",
    "caput succedaneum", "cardiac arrest neonatal", "cardiomyopathy neonatal",
    "cardio-respiratory arrest neonatal", "cephalhaematoma", "cerebral haemorrhage neonatal",
    "circulatory failure neonatal", "cleft lip repair", "cleft palate repair",
    "coagulation disorder neonatal", "coma neonatal", "constipation neonatal",
    "coxsackie viral disease of the newborn", "cranial nerve injury secondary to birth trauma",
    "cranial sutures widening", "cyanosis neonatal", "death neonatal",
    "delayed closure of cranial sutures", "delayed fontanelle closure",
    "diarrhoea infectious neonatal", "diarrhoea neonatal", "disseminated intravascular coagulation in newborn",
    "disturbance of thermoregulation of newborn", "drug withdrawal syndrome neonatal",
    "dry lung syndrome", "dyskinesia neonatal", "early infantile epileptic encephalopathy with burst-suppression",
    "eczema infantile", "encephalopathy neonatal", "endocardial cushion defect repair",
    "epileptic encephalopathy", "erythema toxicum neonatorum", "facial nerve injury due to birth trauma",
    "feeding intolerance", "fever neonatal", "finnegan score increased",
    "fixed bowel loop", "floppy infant", "fontanelle bulging", "fontanelle depressed",
    "fracture of clavicle due to birth trauma", "funisitis", "gangrene neonatal",
    "gasping syndrome", "granulocytopenia neonatal", "grey syndrome neonatal",
    "group b streptococcus neonatal sepsis", "haemolysis neonatal",
    "haemorrhage neonatal", "haemorrhagic disease of newborn", "head circumference abnormal",
    "hepatitis neonatal", "hepatocellular damage neonatal", "hepatosplenomegaly neonatal",
    "herpes simplex virus conjunctivitis neonatal", "high-pitched crying",
    "hygroma colli", "hyperbilirubinaemia neonatal", "hyperkinesia neonatal",
    "hypertension neonatal", "hypertonia neonatal", "hypoglycaemia neonatal",
    "hypokinesia neonatal", "hypothermia neonatal", "hypotonia neonatal",
    "hypoventilation neonatal", "hypoxic ischaemic encephalopathy neonatal",
    "immature larynx", "immature respiratory system", "inclusion conjunctivitis neonatal",
    "incubator therapy", "infant dyschezia", "infant irritability",
    "infant sedation", "infantile acropustulosis", "infantile apnoea",
    "infantile back arching", "infantile colic", "infantile haemangioma",
    "infantile postural asymmetry", "infantile scurvy", "infantile spasms",
    "infantile spitting up", "infantile vomiting", "injury to brachial plexus due to birth trauma",
    "injury to spinal cord secondary to birth trauma", "intoxication by breast feeding",
    "intracranial haemorrhage neonatal", "intraventricular haemorrhage neonatal",
    "isoimmune haemolytic disease", "jaundice neonatal", "junctional ectopic tachycardia",
    "kernicterus", "late metabolic acidosis of newborn", "lenticulostriatal vasculopathy",
    "leukopenia neonatal", "low birth weight baby", "lymphocytopenia neonatal",
    "meconium abnormal", "meconium aspiration syndrome", "meconium cyst",
    "meconium ileus", "meconium plug syndrome", "melaena neonatal",
    "meningitis neonatal", "meningoencephalitis herpes simplex neonatal",
    "midline head position", "myasthenia gravis neonatal", "necrotising enterocolitis neonatal",
    "neonatal alveolar aeration excessive", "neonatal anoxia", "neonatal anuria",
    "neonatal asphyxia", "neonatal aspiration", "neonatal bacteraemia",
    "neonatal behavioural syndrome", "neonatal bradyarrhythmia",
    "neonatal candida infection", "neonatal cardiac failure", "neonatal cholestasis",
    "neonatal complications of substance abuse", "neonatal crohn's disease",
    "neonatal deafness", "neonatal deformity", "neonatal diabetes mellitus",
    "neonatal disorder", "neonatal dyspnoea", "neonatal epileptic seizure",
    "neonatal exchange blood transfusion", "neonatal gastrointestinal disorder",
    "neonatal gastrointestinal haemorrhage", "neonatal hepatomegaly",
    "neonatal hyperglycaemia", "neonatal hypoacusis", "neonatal hypocalcaemia",
    "neonatal hyponatraemia", "neonatal hypoparathyroidism", "neonatal hypotension",
    "neonatal hypoxia", "neonatal infection", "neonatal infective mastitis",
    "neonatal intestinal dilatation", "neonatal intestinal obstruction",
    "neonatal intestinal perforation", "neonatal mucocutaneous herpes simplex",
    "neonatal multi-organ failure", "neonatal neuroblastoma", "neonatal oversedation",
    "neonatal pneumonia", "neonatal pneumothorax", "neonatal respiratory acidosis",
    "neonatal respiratory alkalosis", "neonatal respiratory arrest",
    "neonatal respiratory depression", "neonatal respiratory distress",
    "neonatal respiratory distress syndrome", "neonatal respiratory distress syndrome prophylaxis",
    "neonatal respiratory failure", "neonatal seizure", "neonatal sinus bradycardia",
    "neonatal sinus tachycardia", "neonatal tachyarrhythmia", "neonatal tachycardia",
    "neonatal tachypnoea", "neonatal testicular torsion", "neonatal tetany",
    "neonatal thyrotoxicosis", "neonatal toxicity", "neonatal warming therapy",
    "neuroendocrine cell hyperplasia of infancy", "neutropenia neonatal",
    "norwood procedure", "oedema neonatal", "omphalitis", "ophthalmia neonatorum",
    "overfeeding of infant", "parenteral nutrition associated liver disease",
    "patent ductus arteriosus repair", "perinatal brain damage",
    "perinatal hbv infection", "perinatal hiv infection", "perinatal stroke",
    "peripheral oedema neonatal", "periventricular haemorrhage neonatal",
    "periventricular leukomalacia", "polycythaemia neonatorum", "poor feeding infant",
    "poor sucking reflex", "poor weight gain neonatal", "posthaemorrhagic hydrocephalus",
    "postmature baby", "postnatal growth restriction", "premature baby",
    "pulmonary air leakage", "pulmonary dysmaturity syndrome", "pulmonary haemorrhage neonatal",
    "pulmonary oedema neonatal", "purpura neonatal", "pyloromyotomy",
    "rash neonatal", "renal failure neonatal", "renal impairment neonatal",
    "repair of imperforate rectum", "respiratory disorder neonatal",
    "respiratory tract haemorrhage neonatal", "retinopathy of prematurity",
    "scalp injury due to birth trauma", "sepsis neonatal", "small fontanelle",
    "small for dates baby", "somnolence neonatal", "sporadic infantile bilateral striatal necrosis",
    "subarachnoid haemorrhage neonatal", "subdural haemorrhage neonatal",
    "subgaleal haematoma", "subgaleal haemorrhage", "suck-swallow breathing coordination disturbance",
    "sudden infant death syndrome", "systemic-pulmonary artery shunt",
    "tetanus neonatorum", "tetralogy of fallot repair", "thrombocytopenia neonatal",
    "thrombophlebitis neonatal", "transient hypogammaglobulinaemia of infancy",
    "transient hypothyroxinaemia of prematurity", "transient neonatal pustular melanosis",
    "transient tachypnoea of the newborn", "tremor neonatal", "truncus arteriosus repair",
    "umbilical discharge", "umbilical granuloma", "umbilical sepsis",
    "urinary tract infection neonatal", "venous thrombosis neonatal",
    "ventricular septal defect repair", "vision abnormal neonatal",
    "weight decrease neonatal", "abnormal product of conception",
    "aborted pregnancy", "abortion", "abortion complete", "abortion complete complicated",
    "abortion complicated", "abortion early", "abortion incomplete",
    "abortion incomplete complicated", "abortion induced", "abortion induced complete",
    "abortion induced complete complicated", "abortion induced complicated",
    "abortion induced incomplete", "abortion induced incomplete complicated",
    "abortion infected", "abortion late", "abortion missed", "abortion of ectopic pregnancy",
    "abortion spontaneous", "abortion spontaneous complete", "abortion spontaneous complete complicated",
    "abortion spontaneous complicated", "abortion spontaneous incomplete",
    "abortion spontaneous incomplete complicated", "abortion threatened",
    "anembryonic gestation", "biochemical pregnancy", "evacuation of retained products of conception",
    "foetal death", "foeticide", "habitual abortion", "imminent abortion",
    "induced abortion failed", "induced abortion haemorrhage", "induced abortion infection",
    "lithopedion", "molar abortion", "mycoplasmal postabortal fever",
    "post abortion complication", "post abortion haemorrhage", "post abortion infection",
    "premature baby death", "selective abortion", "stillbirth", "vacuum aspiration",
    "vanishing twin syndrome"
  ))


  ## exposures -------------------
  exposure_def <- c(
    "maternal exposure during delivery",
    "foetal exposure during delivery",
    "maternal exposure before pregnancy",
    "maternal exposure during pregnancy",
    "foetal exposure during pregnancy",
    "exposure during pregnancy",
    "maternal exposure timing unspecified",
    "foetal exposure timing unspecified",
    "maternal drugs affecting foetus",
    "drug exposure before pregnancy"
  )

  exposure_pat_def <- c(
    "paternal drugs affecting foetus",
    "exposure via father",
    "paternal exposure during pregnancy",
    "paternal exposure timing unspecified",
    "paternal exposure before pregnancy",
    "maternal exposure via partner during pregnancy"
  )


  import("DEMO")
  import("DRUG")
  import("REAC")
  import("INDI")
  import("OUTC")
  import("THER")
  import("DRUG_SUPP")
  # Step 1 - Pregnancy reports---------------------------------
  indi_preg <- unique(Indi[indi_pt %in% pregnancy_indication]$primaryid)

  reac_preg <- unique(Reac[pt %in% pregnancy_reaction]$primaryid)

  route_preg <- union(
    union(
      Indi[indi_pt %in% exposure_def]$primaryid,
      Reac[pt %in% exposure_def]$primaryid
    ),
    Drug_supp[route %in% c(
      "transplacental",
      "intraamniotic", "extraamniotic"
    )]$primaryid
  )

  step1_pregn <- union(union(indi_preg, reac_preg), route_preg)
  paternal_exposure <- union(
    Indi[indi_pt %in% exposure_pat_def]$primaryid,
    Reac[pt %in% exposure_pat_def]$primaryid
  )
  low_specificity <- setdiff(step1_pregn, paternal_exposure)
  # Definitive pregnancy---------------------------------
  preg_exp_pids <- intersect(
    union(
      Indi[indi_pt %in% exposure_def]$primaryid,
      Reac[pt %in% exposure_def]$primaryid
    ),
    low_specificity
  )

  transp_pids <- intersect(
    Drug_supp[route %in% c(
      "transplacental",
      "intraamniotic", "extraamniotic"
    )]$primaryid,
    low_specificity
  )

  high_specificity <- union(preg_exp_pids, transp_pids)
  # Exclusion criteria -----------------------------------
  other_pregnancy_pids <- setdiff(low_specificity, high_specificity)

  children_pids <- intersect(
    union(
      Indi[indi_pt %in% child_def]$primaryid,
      Demo[age_in_days < 15 * 365]$primaryid
    ),
    other_pregnancy_pids
  )

  other_pregnancy_pids <- setdiff(other_pregnancy_pids, children_pids)

  male_or_na_pids <- intersect(Demo[sex == "M" | is.na(sex)]$primaryid, other_pregnancy_pids)

  other_pregnancy_pids <- setdiff(other_pregnancy_pids, male_or_na_pids)

  age_ineligible <- intersect(Demo[age_in_days >= 55 * 365 | is.na(age_in_days)]$primaryid, other_pregnancy_pids)

  other_pregnancy_pids <- setdiff(other_pregnancy_pids, age_ineligible)

  medium_specificity <- union(high_specificity, other_pregnancy_pids)
  results <- list(
    "high_specificity" = high_specificity,
    "medium_specificity" = medium_specificity,
    "low_specificity" = low_specificity,
    "paternal_exposure" = paternal_exposure
  )
  return(results)
}
